### ISSUE TITLE
Sigma is not positive semi-definite in Simple portfolio optimization

### ISSUE THREAD

**Issue by juliomorero** [cvxgrp/cvx_short_course#4]
Hi! First of all, I apologize if this is something that was already taken into account or not the appropriate place to comment this.

I came across this repo in [Boyd's website](https://web.stanford.edu/~boyd/papers/cvx_short_course.html) and decided to follow the exercises. Then, when I tried to optimize the problem an error occurred saying the objective wasn't DCP. After a while, comparing with [Boyd's notebook](https://nbviewer.org/github/cvxgrp/cvx_short_course/blob/master/applications/portfolio_optimization.ipynb), I noticed that `Sigma` wasn't being positive semi-definite, and thus not convex. 

![Screen Shot 2022-06-22 at 7 05 26 PM](https://user-images.githubusercontent.com/29715691/175160357-637bf0c2-3a64-4989-a36f-b3205a421f36.png)

Does this make sense or is it just due to the randomness when creating the values?

**Comment by phschiele** [comment]
Great spot @juliomorero, thanks for mentioning it here!
`S = S.T * S` in line 9 should be `S = S.T @ S`.
